// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-recent-inquiries.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_inquiries_default = defineTool({
  name: "list_recent_inquiries",
  title: "List recent inquiries",
  description: "List the most recent customer inquiries (leads). Returns id, name, phone, city/address, service type, status, created_at.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("How many to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await userClient(ctx).from("inquiries").select("id, name, phone, email, address, service_type, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-inquiry.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_inquiry_default = defineTool2({
  name: "get_inquiry",
  title: "Get inquiry",
  description: "Fetch full details of a single inquiry by id, including description and attribution.",
  inputSchema: { id: z2.string().uuid().describe("Inquiry UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await userClient2(ctx).from("inquiries").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { inquiry: data } };
  }
});

// src/lib/mcp/tools/search-inquiries.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function userClient3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_inquiries_default = defineTool3({
  name: "search_inquiries",
  title: "Search inquiries",
  description: "Filter inquiries by status, city substring, service type, and/or date range.",
  inputSchema: {
    status: z3.string().optional().describe("Exact status value, e.g. 'new', 'contacted'."),
    city: z3.string().optional().describe("Case-insensitive substring match on address."),
    service_type: z3.string().optional().describe("Exact service_type value."),
    since: z3.string().optional().describe("ISO date/datetime, inclusive lower bound on created_at."),
    until: z3.string().optional().describe("ISO date/datetime, inclusive upper bound on created_at."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, city, service_type, since, until, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = userClient3(ctx).from("inquiries").select("id, name, phone, email, address, service_type, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (service_type) q = q.eq("service_type", service_type);
    if (city) q = q.ilike("address", `%${city}%`);
    if (since) q = q.gte("created_at", since);
    if (until) q = q.lte("created_at", until);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { inquiries: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-call-log.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function userClient4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_call_log_default = defineTool4({
  name: "list_call_log",
  title: "List call log entries",
  description: "Recent entries from the CRM call log.",
  inputSchema: { limit: z4.number().int().min(1).max(100).optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await userClient4(ctx).from("call_log").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { calls: data ?? [] } };
  }
});

// src/lib/mcp/tools/inquiry-stats.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
function userClient5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var inquiry_stats_default = defineTool5({
  name: "inquiry_stats",
  title: "Inquiry statistics",
  description: "Counts of inquiries in the last N days, aggregated by status and by day.",
  inputSchema: { days: z5.number().int().min(1).max(365).optional().describe("Window size, default 30.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const windowDays = days ?? 30;
    const since = new Date(Date.now() - windowDays * 864e5).toISOString();
    const { data, error } = await userClient5(ctx).from("inquiries").select("status, created_at").gte("created_at", since);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byStatus = {};
    const byDay = {};
    for (const row of data ?? []) {
      byStatus[row.status ?? "unknown"] = (byStatus[row.status ?? "unknown"] ?? 0) + 1;
      const day = row.created_at.slice(0, 10);
      byDay[day] = (byDay[day] ?? 0) + 1;
    }
    const summary = { windowDays, total: data?.length ?? 0, byStatus, byDay };
    return { content: [{ type: "text", text: JSON.stringify(summary, null, 2) }], structuredContent: summary };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.25.76";
function userClient6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_articles_default = defineTool6({
  name: "list_articles",
  title: "List blog articles",
  description: "List blog articles managed in the CMS with title, slug, status, and view count.",
  inputSchema: {
    status: z6.enum(["draft", "published"]).optional(),
    limit: z6.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = userClient6(ctx).from("articles").select("id, title, slug, status, views, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 30);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { articles: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vpsbqrxrjrwjmttnptfr";
var mcp_default = defineMcp({
  name: "remont-pokrivi-varna-mcp",
  title: "\u0420\u0435\u043C\u043E\u043D\u0442 \u043D\u0430 \u043F\u043E\u043A\u0440\u0438\u0432\u0438 \u0412\u0430\u0440\u043D\u0430 \u2014 CRM",
  version: "0.1.0",
  instructions: "Read-only CRM tools for the Remont Pokrivi Varna app. Use these to query customer inquiries (leads), call log entries, and blog articles. All queries run under the signed-in user's row-level permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_inquiries_default, get_inquiry_default, search_inquiries_default, list_call_log_default, inquiry_stats_default, list_articles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
